# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='chatpb',
  syntax='proto3',
  serialized_options=b'Z\010./chatpb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nchat.proto\x12\x06\x63hatpb\"-\n\x07\x43hannel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0csenders_name\x18\x02 \x01(\t\"L\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12 \n\x07\x63hannel\x18\x02 \x01(\x0b\x32\x0f.chatpb.Channel\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1c\n\nMessageAck\x12\x0e\n\x06status\x18\x01 \x01(\t2z\n\x0b\x43hatService\x12\x33\n\x0bJoinChannel\x12\x0f.chatpb.Channel\x1a\x0f.chatpb.Message\"\x00\x30\x01\x12\x36\n\x0bSendMessage\x12\x0f.chatpb.Message\x1a\x12.chatpb.MessageAck\"\x00(\x01\x42\nZ\x08./chatpbb\x06proto3'
)




_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='chatpb.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='chatpb.Channel.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='senders_name', full_name='chatpb.Channel.senders_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=67,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='chatpb.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='chatpb.Message.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel', full_name='chatpb.Message.channel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='chatpb.Message.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=145,
)


_MESSAGEACK = _descriptor.Descriptor(
  name='MessageAck',
  full_name='chatpb.MessageAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='chatpb.MessageAck.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=175,
)

_MESSAGE.fields_by_name['channel'].message_type = _CHANNEL
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['MessageAck'] = _MESSAGEACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
  'DESCRIPTOR' : _CHANNEL,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatpb.Channel)
  })
_sym_db.RegisterMessage(Channel)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatpb.Message)
  })
_sym_db.RegisterMessage(Message)

MessageAck = _reflection.GeneratedProtocolMessageType('MessageAck', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEACK,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatpb.MessageAck)
  })
_sym_db.RegisterMessage(MessageAck)


DESCRIPTOR._options = None

_CHATSERVICE = _descriptor.ServiceDescriptor(
  name='ChatService',
  full_name='chatpb.ChatService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=177,
  serialized_end=299,
  methods=[
  _descriptor.MethodDescriptor(
    name='JoinChannel',
    full_name='chatpb.ChatService.JoinChannel',
    index=0,
    containing_service=None,
    input_type=_CHANNEL,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='chatpb.ChatService.SendMessage',
    index=1,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGEACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVICE)

DESCRIPTOR.services_by_name['ChatService'] = _CHATSERVICE

# @@protoc_insertion_point(module_scope)
