<Accel>:
    Label:
        id: label1
        pos: 150, 300
        text: 'X: '
    Label:
        id: label2
        pos: 150, 250
        text: 'Y: '
    Label:
        id: label3
        pos: 150, 200
        text: 'Z: '
    Label:
        id: status
        pos: 150, 150
        text: ''
    Button:
        id: button1
        pos: 150, 50
        text: 'Start'
        on_press: root.pressed1()

