# Generated by Django 4.0.4 on 2022-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloworld", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helloworldprocess",
            name="suggestion",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
