# Generated by Django 3.2.3 on 2021-06-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_auto_20210604_0652"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="answerrecord",
            index_together={("question_id", "user_id")},
        ),
    ]
